#############################################################################
# Makefile for building: cfgtest_QtScriptTools
# Generated by qmake (2.01a) (Qt 4.8.7) on: mar. juin 28 15:29:41 2016
# Project:  cfgtest_QtScriptTools.pro
# Template: app
# Command: /home/innopolis/anaconda2/bin/qmake -o cfgtest_QtScriptTools.mk cfgtest_QtScriptTools.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_SCRIPTTOOLS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../anaconda2/mkspecs/linux-g++ -I. -I../../../../anaconda2/include/QtCore -I../../../../anaconda2/include/QtGui -I../../../../anaconda2/include/QtScriptTools -I../../../../anaconda2/include/QtScript -I../../../../anaconda2/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/innopolis/anaconda2/lib
LIBS          = $(SUBLIBS)  -L/home/innopolis/anaconda2/lib -L/home/innopolis/anaconda2/lib -lQtScriptTools -lQtScript -L/usr/X11R6/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/innopolis/anaconda2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cfgtest_QtScriptTools.cpp 
OBJECTS       = cfgtest_QtScriptTools.o
DIST          = ../../../../anaconda2/mkspecs/common/unix.conf \
		../../../../anaconda2/mkspecs/common/linux.conf \
		../../../../anaconda2/mkspecs/common/gcc-base.conf \
		../../../../anaconda2/mkspecs/common/gcc-base-unix.conf \
		../../../../anaconda2/mkspecs/common/g++-base.conf \
		../../../../anaconda2/mkspecs/common/g++-unix.conf \
		../../../../anaconda2/mkspecs/qconfig.pri \
		../../../../anaconda2/mkspecs/modules/qt_webkit_version.pri \
		../../../../anaconda2/mkspecs/features/qt_functions.prf \
		../../../../anaconda2/mkspecs/features/qt_config.prf \
		../../../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../../../anaconda2/mkspecs/features/default_pre.prf \
		../../../../anaconda2/mkspecs/features/release.prf \
		../../../../anaconda2/mkspecs/features/default_post.prf \
		../../../../anaconda2/mkspecs/features/shared.prf \
		../../../../anaconda2/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../anaconda2/mkspecs/features/warn_on.prf \
		../../../../anaconda2/mkspecs/features/qt.prf \
		../../../../anaconda2/mkspecs/features/unix/thread.prf \
		../../../../anaconda2/mkspecs/features/moc.prf \
		../../../../anaconda2/mkspecs/features/resources.prf \
		../../../../anaconda2/mkspecs/features/uic.prf \
		../../../../anaconda2/mkspecs/features/yacc.prf \
		../../../../anaconda2/mkspecs/features/lex.prf \
		../../../../anaconda2/mkspecs/features/include_source_dir.prf \
		cfgtest_QtScriptTools.pro
QMAKE_TARGET  = cfgtest_QtScriptTools
DESTDIR       = 
TARGET        = cfgtest_QtScriptTools

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: cfgtest_QtScriptTools.mk $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

cfgtest_QtScriptTools.mk: cfgtest_QtScriptTools.pro  ../../../../anaconda2/mkspecs/linux-g++/qmake.conf ../../../../anaconda2/mkspecs/common/unix.conf \
		../../../../anaconda2/mkspecs/common/linux.conf \
		../../../../anaconda2/mkspecs/common/gcc-base.conf \
		../../../../anaconda2/mkspecs/common/gcc-base-unix.conf \
		../../../../anaconda2/mkspecs/common/g++-base.conf \
		../../../../anaconda2/mkspecs/common/g++-unix.conf \
		../../../../anaconda2/mkspecs/qconfig.pri \
		../../../../anaconda2/mkspecs/modules/qt_webkit_version.pri \
		../../../../anaconda2/mkspecs/features/qt_functions.prf \
		../../../../anaconda2/mkspecs/features/qt_config.prf \
		../../../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../../../anaconda2/mkspecs/features/default_pre.prf \
		../../../../anaconda2/mkspecs/features/release.prf \
		../../../../anaconda2/mkspecs/features/default_post.prf \
		../../../../anaconda2/mkspecs/features/shared.prf \
		../../../../anaconda2/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../anaconda2/mkspecs/features/warn_on.prf \
		../../../../anaconda2/mkspecs/features/qt.prf \
		../../../../anaconda2/mkspecs/features/unix/thread.prf \
		../../../../anaconda2/mkspecs/features/moc.prf \
		../../../../anaconda2/mkspecs/features/resources.prf \
		../../../../anaconda2/mkspecs/features/uic.prf \
		../../../../anaconda2/mkspecs/features/yacc.prf \
		../../../../anaconda2/mkspecs/features/lex.prf \
		../../../../anaconda2/mkspecs/features/include_source_dir.prf \
		/home/innopolis/anaconda2/lib/libQtScript.prl \
		/home/innopolis/anaconda2/lib/libQtCore.prl \
		/home/innopolis/anaconda2/lib/libQtScriptTools.prl \
		/home/innopolis/anaconda2/lib/libQtGui.prl
	$(QMAKE) -o cfgtest_QtScriptTools.mk cfgtest_QtScriptTools.pro
../../../../anaconda2/mkspecs/common/unix.conf:
../../../../anaconda2/mkspecs/common/linux.conf:
../../../../anaconda2/mkspecs/common/gcc-base.conf:
../../../../anaconda2/mkspecs/common/gcc-base-unix.conf:
../../../../anaconda2/mkspecs/common/g++-base.conf:
../../../../anaconda2/mkspecs/common/g++-unix.conf:
../../../../anaconda2/mkspecs/qconfig.pri:
../../../../anaconda2/mkspecs/modules/qt_webkit_version.pri:
../../../../anaconda2/mkspecs/features/qt_functions.prf:
../../../../anaconda2/mkspecs/features/qt_config.prf:
../../../../anaconda2/mkspecs/features/exclusive_builds.prf:
../../../../anaconda2/mkspecs/features/default_pre.prf:
../../../../anaconda2/mkspecs/features/release.prf:
../../../../anaconda2/mkspecs/features/default_post.prf:
../../../../anaconda2/mkspecs/features/shared.prf:
../../../../anaconda2/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../anaconda2/mkspecs/features/warn_on.prf:
../../../../anaconda2/mkspecs/features/qt.prf:
../../../../anaconda2/mkspecs/features/unix/thread.prf:
../../../../anaconda2/mkspecs/features/moc.prf:
../../../../anaconda2/mkspecs/features/resources.prf:
../../../../anaconda2/mkspecs/features/uic.prf:
../../../../anaconda2/mkspecs/features/yacc.prf:
../../../../anaconda2/mkspecs/features/lex.prf:
../../../../anaconda2/mkspecs/features/include_source_dir.prf:
/home/innopolis/anaconda2/lib/libQtScript.prl:
/home/innopolis/anaconda2/lib/libQtCore.prl:
/home/innopolis/anaconda2/lib/libQtScriptTools.prl:
/home/innopolis/anaconda2/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o cfgtest_QtScriptTools.mk cfgtest_QtScriptTools.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cfgtest_QtScriptTools1.0.0 || $(MKDIR) .tmp/cfgtest_QtScriptTools1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cfgtest_QtScriptTools1.0.0/ && $(COPY_FILE) --parents cfgtest_QtScriptTools.cpp .tmp/cfgtest_QtScriptTools1.0.0/ && (cd `dirname .tmp/cfgtest_QtScriptTools1.0.0` && $(TAR) cfgtest_QtScriptTools1.0.0.tar cfgtest_QtScriptTools1.0.0 && $(COMPRESS) cfgtest_QtScriptTools1.0.0.tar) && $(MOVE) `dirname .tmp/cfgtest_QtScriptTools1.0.0`/cfgtest_QtScriptTools1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cfgtest_QtScriptTools1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) cfgtest_QtScriptTools.mk


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

cfgtest_QtScriptTools.o: cfgtest_QtScriptTools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cfgtest_QtScriptTools.o cfgtest_QtScriptTools.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

